# Generated by Codex on 2026-01-19

import uuid
from django.db import migrations, models


def populate_folder_uuid(apps, schema_editor):
    Folder = apps.get_model("editor", "Folder")
    for folder in Folder.objects.filter(uuid__isnull=True):
        folder.uuid = uuid.uuid4()
        folder.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0003_report_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="folder",
            name="uuid",
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
        migrations.RunPython(populate_folder_uuid, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="folder",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
